apiVersion: v1
kind: ReplicationController
metadata:
  name: blue
  labels:
    app: blue
    tier: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: blue
  template:
    metadata:
      labels:
        tier: blue
    spec:
      containers:
      - name: blue
        image: cbirdsey1/devopscapstone